name: Build & Test

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # STEP 1: Compilação e Testes Unitários (Rápido)
      # Aqui o Maven usará o H2 definido no application-test.properties
      - name: Unit Tests & Compile
        run: mvn clean test -Dtest="!*IntegrationTest"
        working-directory: ./springboot_app

      # STEP 2: Testes de Integração (Docker com Testcontainers)
      # Só corre se os unitários passarem.
      - name: Integration Tests
        run: mvn verify -Pintegration-test -Dtest="*IntegrationTest"
        working-directory: ./springboot_app

      # STEP 3: Verificação de Qualidade (JaCoCo)
      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: springboot_app/target/site/jacoco/